name: aeropt-hpc
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.23,<2.0
  - scipy>=1.10,<1.12
  - scikit-learn>=1.3.0
  - vtk>=9.2,<9.4
  - pyvista>=0.42,<0.44
  - shapely>=2.1.1
  - alphashape>=1.3.1
  - matplotlib>=3.10.3
  - pandas
  - networkx>=3.4,<3.5
  - pip
  - pip:
      - paramiko>=3.4,<4.0
      - tqdm>=4.66,<5.0
      - cma>=4.4.0
